metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 10s
  reload.enabled: false
metricbeat.max_start_delay: 10s
metricbeat.modules:
- module: prometheus
  period: 10s
  metricsets: ["collector"]
  hosts: ["pump:9999"]
  metrics_path: /metrics
#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: ["elasticsearch:9200"]